config change

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1594,6 +1594,61 @@ jobs:
           root: ~/workspace
           paths:
             - Part_Fourteen_daily-build-and-test-14_TEST-*.xml
+    executor:
+
+  daily-build-and-test-15:
+    docker:
+      - image: cimg/base:stable
+    resource_class: xlarge
+    steps:
+      - checkout
+      - run:
+          name: Install Java 22
+          command: |
+            sudo apt-get update && sudo apt-get install -y wget
+            wget https://download.java.net/java/GA/jdk22/830ec9fcccef480bb3e73fb7ecafe059/36/GPL/openjdk-22_linux-x64_bin.tar.gz
+            sudo mkdir -p /usr/lib/jvm
+            sudo tar zxvf openjdk-22_linux-x64_bin.tar.gz -C /usr/lib/jvm
+            sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk-22/bin/java 2200
+            sudo update-alternatives --config java
+            echo 'export PATH="/usr/lib/jvm/jdk-22/bin:$PATH"' >> $BASH_ENV
+            source $BASH_ENV
+            java -version
+      - run:
+          name: Install Maven
+          command: |
+            sudo apt-get install -y maven
+            mvn -version
+      - run:
+          name: Install Chrome
+          command: |
+            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
+            sudo apt-get update
+            sudo apt-get install -y google-chrome-stable
+            google-chrome --version
+      - run:
+          name: Build and run daily tests 15
+          command: mvn clean test -Dsurefire.suiteXmlFiles=regression15.xml -Drun.headless=true -Dtest.env=stag -Dcreate.cycle=true || true
+      - store_artifacts:
+          path: target/surefire-reports
+          destination: daily-build-and-test-artifacts-15
+      - run:
+          name: Verify Test Results Exist
+          command: ls -R target/surefire-reports || echo "Test results missing!"
+      - run:
+          name: Copy test results to workspace
+          command: |
+            mkdir -p ~/workspace
+            PART_NAME="Part_Fifteen"
+            for file in target/surefire-reports/TEST-*.xml; do
+              [ -f "$file" ] && cp "$file" ~/workspace/${PART_NAME}_daily-build-and-test-15_$(basename "$file")
+            done
+      - persist_to_workspace:
+          root: ~/workspace
+          paths:
+            - Part_Fifteen_daily-build-and-test-15_TEST-*.xml
+    executor:
 
   calculate-pass-fail-rate:
     docker:
@@ -1817,56 +1872,58 @@ workflows:
 #            - nightly-build-and-test-13
 #            - nightly-build-and-test-14
 
-#  scheduled-test-2:
-#    triggers:
-#      - schedule:
-#          cron: "00 04 * * 1-5"  # This will run daily-build-and-test at 11:15 AM IST (05:45 AM UTC) // 45 05
-#          filters:
-#           branches:
-#              only:
-#                - main
-#    jobs:
-#      - daily-build-and-test-1
-#      - daily-build-and-test-2
-#      - daily-build-and-test-3
-#      - daily-build-and-test-4
-#      - daily-build-and-test-5
-#      - daily-build-and-test-7
-#      - calculate-pass-fail-rate:
-#          requires:
-#            - daily-build-and-test-1
-#            - daily-build-and-test-2
-#            - daily-build-and-test-3
-#            - daily-build-and-test-4
-#            - daily-build-and-test-5
-#            - daily-build-and-test-7
+  scheduled-test-2:
+    triggers:
+      - schedule:
+          cron: "00 06 * * 1-5"  # This will run daily-build-and-test at 11:15 AM IST (05:45 AM UTC) // 45 05
+          filters:
+           branches:
+              only:
+                - staging_regression
+    jobs:
+      - daily-build-and-test-1
+      - daily-build-and-test-2
+      - daily-build-and-test-3
+      - daily-build-and-test-4
+      - daily-build-and-test-5
+      - daily-build-and-test-7
+      - calculate-pass-fail-rate:
+          requires:
+            - daily-build-and-test-1
+            - daily-build-and-test-2
+            - daily-build-and-test-3
+            - daily-build-and-test-4
+            - daily-build-and-test-5
+            - daily-build-and-test-7
 
-#  scheduled-test-2-sub1:
-#    triggers:
-#     - schedule:
-#          cron: "00 05 * * 1-5"  # This will run nightly-build-and-test at 2:00 AM IST (08:30 PM UTC) -- 45 06 * * *
-#          filters:
-#            branches:
-#              only:
-#                - main
-#    jobs:
-#      - daily-build-and-test-6
-#      - daily-build-and-test-8
-#      - daily-build-and-test-9
-#      - daily-build-and-test-10
-#      - daily-build-and-test-11
-#      - daily-build-and-test-12
-#      - daily-build-and-test-13
-#      - daily-build-and-test-14
-#      - calculate-pass-fail-rate:
-#          requires:
-#            - daily-build-and-test-6
-#            - daily-build-and-test-8
-#            - daily-build-and-test-9
-#            - daily-build-and-test-10
-#            - daily-build-and-test-11
-#            - daily-build-and-test-12
-#            - daily-build-and-test-13
-#            - daily-build-and-test-14
+  scheduled-test-2-sub1:
+    triggers:
+     - schedule:
+          cron: "00 07 * * 1-5"  # This will run nightly-build-and-test at 2:00 AM IST (08:30 PM UTC) -- 45 06 * * *
+          filters:
+            branches:
+              only:
+                - staging_regression
+    jobs:
+      - daily-build-and-test-6
+      - daily-build-and-test-8
+      - daily-build-and-test-9
+      - daily-build-and-test-10
+      - daily-build-and-test-11
+      - daily-build-and-test-12
+      - daily-build-and-test-13
+      - daily-build-and-test-14
+      - daily-build-and-test-15
+      - calculate-pass-fail-rate:
+          requires:
+            - daily-build-and-test-6
+            - daily-build-and-test-8
+            - daily-build-and-test-9
+            - daily-build-and-test-10
+            - daily-build-and-test-11
+            - daily-build-and-test-12
+            - daily-build-and-test-13
+            - daily-build-and-test-14
+            - daily-build-and-test-15
 
 
